---

header_template: "# %new_version / %release_date"

entry_template: "* %title. Pull request #%pull_request_number by %pull_request_author"

extra_entry:
  template: "* %title."
  label: "rubygems: enhancement"

release_date_format: "%Y-%m-%d"

entry_wrapping: 74

changelog_label_mapping:
  "rubygems: security fix": "## Security fixes:"
  "rubygems: breaking change": "## Breaking changes:"
  "rubygems: deprecation": "## Deprecations:"
  "rubygems: feature": "## Features:"
  "rubygems: performance": "## Performance:"
  "rubygems: enhancement": "## Enhancements:"
  "rubygems: bug fix": "## Bug fixes:"
  "rubygems: documentation": "## Documentation:"
  "rubygems: backport": null

patch_level_labels:
  - "rubygems: security fix"
  - "rubygems: deprecation"
  - "rubygems: enhancement"
  - "rubygems: bug fix"
  - "rubygems: performance"
  - "rubygems: documentation"
  - "rubygems: backport"
