---

header_template: "# %new_version (%release_date)"

entry_template: "  - %title [#%pull_request_number](%pull_request_url)"

release_date_format: "%B %-d, %Y"

changelog_label_mapping:
  "bundler: security fix": "## Security fixes:"
  "bundler: breaking change": "## Breaking changes:"
  "bundler: deprecation": "## Deprecations:"
  "bundler: feature": "## Features:"
  "bundler: performance": "## Performance:"
  "bundler: enhancement": "## Enhancements:"
  "bundler: bug fix": "## Bug fixes:"
  "bundler: documentation": "## Documentation:"
  "bundler: backport": null

patch_level_labels:
  - "bundler: security fix"
  - "bundler: deprecation"
  - "bundler: enhancement"
  - "bundler: bug fix"
  - "bundler: performance"
  - "bundler: documentation"
  - "bundler: backport"
