name: ubuntu-lint

on:
  pull_request:

  push:
    branches:
      - master
      - 3.3

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  ubuntu_lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3
          bundler: none
      - name: Install Dependencies
        run: rake setup
      - name: Run Lint
        run: rake rubocop
      - name: Generate docs
        run: rake docs
      - name: Install & Check Dependencies
        run: rake dev:frozen_deps
        working-directory: ./bundler
      - name: Misc checks
        run: bin/rake check_rvm_integration man:check check_rubygems_integration
        working-directory: ./bundler
    timeout-minutes: 15
